### ISSUE TITLE
v5.8.5 Endergenic Crash

### ISSUE THREAD

**Issue by MindCaged** [McJty/RFTools#1065]
I just updated to 5.8.5 and tried to setup an Endergenic for the first time in my world, I placed the generators, started linking them together and when I linked the last one back to the first my game crashed and crashes on world load, I was able to get back in by downgrading to 5.8.4. I believe it got caught in an infinite loop going by the error, by the names of the functions I assume it was looking for the generator with the injector, but I hadn't placed one yet.

Error:
```
java.lang.StackOverflowError: Ticking block entity
	at net.minecraft.world.World.func_180495_p(World.java:843)
	at mcjty.rftools.blocks.endergen.EndergenicTileEntity.hasInjector(EndergenicTileEntity.java:214)
	at mcjty.rftools.blocks.endergen.EndergenicTileEntity.findEndergenicWithInjector(EndergenicTileEntity.java:199)
	at mcjty.rftools.blocks.endergen.EndergenicTileEntity.findEndergenicWithInjector(EndergenicTileEntity.java:207)
	at mcjty.rftools.blocks.endergen.EndergenicTileEntity.findEndergenicWithInjector(EndergenicTileEntity.java:207)
	at mcjty.rftools.blocks.endergen.EndergenicTileEntity.findEndergenicWithInjector(EndergenicTileEntity.java:207)
	at mcjty.rftools.blocks.endergen.EndergenicTileEntity.findEndergenicWithInjector(EndergenicTileEntity.java:207)
	at mcjty.rftools.blocks.endergen.EndergenicTileEntity.findEndergenicWithInjector(EndergenicTileEntity.java:207)
	at mcjty.rftools.blocks.endergen.EndergenicTileEntity.findEndergenicWithInjector(EndergenicTileEntity.java:207)
	at mcjty.rftools.blocks.endergen.EndergenicTileEntity.findEndergenicWithInjector(EndergenicTileEntity.java:207)
	at mcjty.rftools.blocks.endergen.EndergenicTileEntity.findEndergenicWithInjector(EndergenicTileEntity.java:207)
```
.... And so on until the end of the error message that last line repeats which is why I believe it's an infinite loop, but I trimmed it off to cut down how spammy it is.

Other Information:
```
-- Block entity being ticked --
Details:
	Name: rftools_endergenic // mcjty.rftools.blocks.endergen.EndergenicTileEntity
	Block type: ID #2697 (tile.rftools.endergenic // mcjty.rftools.blocks.endergen.EndergenicBlock)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-83,11,-10), Chunk: (at 13,0,6 in -6,-1; contains blocks -96,0,-16 to -81,255,-1), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Actual block type: ID #2697 (tile.rftools.endergenic // mcjty.rftools.blocks.endergen.EndergenicBlock)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1810)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by ahollist** [comment]
I also experienced this error, but when breaking a Pearl Injector to remake my Endergenic Generator setup.

**Comment by McJty** [comment]
Will fix

**Comment by McJty** [comment]
Fixed in 5.86 which will hopefully be approved in a few minutes

**Comment by McJty** [comment]
Approved

**Comment by ahollist** [comment]
It's worth noting that this crash was still present in 5.86, when breaking a Pearl Injector, until I picked up the Endergenic Generator it was connected to.

**Comment by McJty** [comment]
That is weird. Can you give me a stacktrace for that and also a description of your setup when this crash happened

**Comment by sandalle** [comment]
Still crashes on mine with rftools 5.86 as well, the world stops itself before any players are on the world.

Minecraft: 1.10.2
Forge Mod Loader: 1.10.2-12.18.3.2239
RFTools: 1.1x-5.86

[crash-2017-03-05_08.36.09-server.txt](https://github.com/McJty/RFTools/files/819453/crash-2017-03-05_08.36.09-server.txt)

**Comment by sandalle** [comment]
Still crashes on mine with rftools 5.86 as well, the world stops itself before any players are on the world.

Minecraft: 1.10.2
Forge Mod Loader: 1.10.2-12.18.3.2239
RFTools: 1.1x-5.86

[crash-2017-03-05_08.36.09-server.txt](https://github.com/McJty/RFTools/files/819453/crash-2017-03-05_08.36.09-server.txt)

**Comment by McJty** [comment]
Fixing now

**Comment by McJty** [comment]
Fixed in 5.87. I hope

**Comment by sandalle** [comment]
rftools 5.87 fixed this bug for me, thank you _very_ much!
