### ISSUE TITLE
[1.12] Storage module 1 in the creative trash slot

### ISSUE THREAD

**Issue by billybricker** [McJty/RFTools#1238]
As the title says there is just a storage module in the trash slot. The trash slot still seems functional and the module cannot be removed.

http://imgur.com/a/oRBhg

Forge: 14.21.0.2343
McJtyLib: 1.12-2.3.1.11beta
RFTools: 1.12-6.02beta

**Comment by McJty** [comment]
I cannot reproduce this and forge has updated a lot since then so I assume this is fixed?

**Comment by billybricker** [comment]
No, it's still happening for me. I evendeleted my .minecraft folder and Curse folder so it had to re-download everything.

![2017-06-28_09 35 18](https://user-images.githubusercontent.com/26291936/27646284-7b6f6594-5be5-11e7-94ea-d2506d5689f0.png)

Forge: 14.21.0.2382
McJtyLib: 1.12-2.40
RFTools: 1.12-6.04

**Comment by McJty** [comment]
Can you tell me what other mods you have?

**Comment by billybricker** [comment]
None. I created a fresh instance after I deleted the Curse and .minecraft folders. It only has Forge, McJtyLib and RFTools installed

**Comment by McJty** [comment]
Ok, I can reproduce this too. VERY weird...

**Comment by billybricker** [comment]
I had a thought. It seems you haven't fixed that creative tab leak[ (thread from /r/ftb about fixing it)](https://www.reddit.com/r/feedthebeast/comments/6h9z7f/psa_the_creativetab_leak_glitch/), Do you think this could somehow be related to that?

**Comment by McJty** [comment]
Fixed next release
