### ISSUE TITLE
Crash When Opening RFTools Manual in Age of Engineering

### ISSUE THREAD

**Issue by liampatterson2** [McJty/RFTools#1319]
I tried to open the manual to read about something, and as soon as I opened it, the game crashed. I restarted the game and tried to open it again and got a crash again. 

I have included the crash reports. 
[crash-2017-08-01_16.43.25-client.txt](https://github.com/McJty/RFTools/files/1191906/crash-2017-08-01_16.43.25-client.txt)
[crash-2017-08-01_16.50.00-client.txt](https://github.com/McJty/RFTools/files/1191905/crash-2017-08-01_16.50.00-client.txt)

**Comment by McJty** [comment]
What version?

**Comment by Aiidoneus** [comment]
@McJty I believe it is version rftools-1.1x-5.92 of rftools. This happens to me as well. Same crash. Both on a server and in a single player instance. If you are curious about the version of Age of Engineering it happens in, it is 1.0.4

**Comment by Aiidoneus** [comment]
#1314 is a duplicate.

**Comment by McJty** [comment]
Very weird. I don't understand why this could happen. Does AoE do anything special with the manual or something?

**Comment by liampatterson2** [comment]
It doesn't do anything special from what I can tell. Default crafting recipe.

**Comment by Metlearm** [comment]
The same thing happens to me.

**Comment by Neurosis404** [comment]
Same here with Infinity Lite. 
Minecraft: 1.10.2
RFtools: rftools-1.1x-5.91
McJity: mcjtylib-1.1x-2.4.3

**Comment by ichmagPopcorn** [comment]
Same here with Age of Engineering 1.1.0
Minecraft 1.10.2
RFtools: rftools-1.1x-5.92
mcjty: mcjtylib-1.1x-2.4.3

crashing when trying to open the manual
https://pastebin.com/gzktzqRv

also crashing when trying to access the manual from a power cell for example
https://pastebin.com/TcR0k1Qx

although the error seems to remain the same

**Comment by frenchiveruti** [comment]
Hi there, Using Age of Engineering 1.1.1c  
Same issue as everyone, this case with the crafter (tier 3) on the ? click:
[crash-2017-10-26_15.44.47-client.txt](https://github.com/McJty/RFTools/files/1419692/crash-2017-10-26_15.44.47-client.txt)
[crash-2017-10-26_15.49.44-client.txt](https://github.com/McJty/RFTools/files/1419694/crash-2017-10-26_15.49.44-client.txt)

Also, here's the log:

[fml-client-latest.log](https://github.com/McJty/RFTools/files/1419698/fml-client-latest.log)

If you need anything else feel free to ask.
I don't really know what mod could cause this interference.

**Comment by frenchiveruti** [comment]
Hey @McJty my log file says something like this:

> [15:49:40] [Client thread/ERROR] [mcjty.lib.varia.Logging/]: Error reading manual text
java.io.FileNotFoundException: rftools:text/manualUS.txt

At line 23798
I think is the root of the issue. Hope that helps.

**Comment by jhultgre** [comment]
That has something to do with it. I extracted the jar and duplicated manual.txt to manualUS.txt and everything looks like it's working.

Although I do get some text that looks like `{rb:smartwrench}` on some pages that I assume should be replaced with something.

**Comment by frenchiveruti** [comment]
Yaay, I'm glad I helped somehow hah.

**Comment by McJty** [comment]
I think this is called by using too old versions. There were some changes around manual.txt around that time and there may have been a mismatch between the version of McJtyLib used back then and rftools

**Comment by jaxx0rr** [comment]
just happened to me too

**Comment by McJty** [comment]
It is not useful to add 'me too' type comments to this issue. I know it happens. No idea why but I think it is solved in more recent versions. The pack needs an update

**Comment by fallenhunter1** [comment]
Working on the manual issue still?

https://pastebin.com/uitAvPmR

Just had it happen to me. Latest version of the pack.
Age of Engineering: 1.1.1c
Forge-12.18.3.2477
Minecraft 1.10.2
Java.. hmm have to look
Version 8 update 131 (build 1.8.0_131-b11)

Open the book, frozen screen, crash to launcher, happened twice.

Anything else I should include in any future reports?

**Comment by McJty** [comment]
I need to know rftools version

**Comment by McJty** [comment]
I will close this issue as this is all with very old versions of RFTools. The packs are simply outdated

**Comment by frenchiveruti** [comment]
He edited the RFT version into his comment, but I think is correct to close it if it's solved.

**Comment by McJty** [comment]
Well I have no idea if it is solved or not but this has only been ever reported for ancient versions of RFTools. As far as I know nobody ever got this bug on recent versions so until then I consider this bug squashed :-)

**Comment by joltak** [comment]
hi, i got crash everytime when i try to open the manual.
i'm in 1.12.2 minecraft version and rftools-1.12-7.23.

The error :
The game crashed whilst updating screen events
The game crashed whilst updating screen events
Error: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
