### ISSUE TITLE
RfTools server crash 1.12-7.20

### ISSUE THREAD

**Issue by MeinKraft** [McJty/RFTools#1525]
RFTools 1.12-7.20
Minecraft 1.12.2
Forge 1.12 2582

Using latest McJty Lib

https://pastebin.com/k9T5bZgY

Game Crash on Dedicated Server

**Comment by McJty** [comment]
Should be fixed in the upcoming 2.6.1 of McJtyLib which is currently waiting for approval on curseforge

**Comment by McJty** [comment]
It is approved; Can you test that it works? Thanks

**Comment by MeinKraft** [comment]
sorry but its still crashing, https://pastebin.com/c952Hs0Q

using mcjty 1.12-2.61

**Comment by McJty** [comment]
RFTools 7.21 is awaiting approval fixing this

**Comment by McJty** [comment]
It is approved

**Comment by HorizonsMC** [comment]
Just updated and got a successful server boot, thanks for the quick fix.
