### ISSUE TITLE
Advanced Porter Server Crash Between Dimensions

### ISSUE THREAD

**Issue by ZacRedact** [McJty/RFTools#686]
http://pastebin.com/RPnJjZNv

I get this crash intermittently when using the Advanced Porter from another dimension (RFTools dimension or the Nether, haven't tested The End) to get back to the overworld. This is on SMP. The server will crash, and when it boots back up the player who caused the crash will be at coords  0,0,0 in the overworld.

**Comment by McJty** [comment]
This crash is in minecraft itself and seems not related to rftools. RFTools is just doing the teleportation. My guess is that you would also crash using other teleportation mechanisms

**Comment by ZacRedact** [comment]
Odd, I haven't had the issue using teleport commands (MyCommands and FTB Utilities). I'll keep an eye out though.

**Comment by helium2s1** [comment]
I've had the same issue on two different modpacks on 1.10.2; Unstable and All The Mods. The porter works fine for a while, then, after a sufficient number of cross-dimensional teleports, it starts crashing the server. Replacing it with a new porter fixes the problem for a while, at least.

**Comment by McJty** [comment]
That doesn't make sense. The porter doesn't even remember or store any information about teleportation. So that replacing a porter works is pure coincidence.

Note that minecraft itself has lots of issues with cross-dimensional teleportation if you do it too much. If the server is up for some time then that might be the issue actually.

**Comment by helium2s1** [comment]
I updated my comment because additional testing revealed that a new porter doesn't always fix it, like you indicated.

The first time I ran into this was when one player was going back and forth to the Aroma1997 Mining Dimension (which had other issues of it's own). The second was while trying to figure out how to make a suitable replacement for that dimension. One thing I noted, that may be unrelated, is that, even after I extracted a realized dimension and rebuilt it with different dimlets, after 2 or 3 times, they started staying in the list in the dialing device. I could teleport to them with no issue, they were still powered up, even without an extent realized dimension tab to run them. I expect that's unrelated, but perhaps both are caused by running into vanilla's cross-dimensional issues.

**Comment by Yusunoha** [comment]
I am also getting this problem on an unstable server I'm playing on, but rather than crashing me it kicks me of the server (I don't know if the server actually crashes or not)

At first I thought it happened when I tried teleporting from one specific dimension (nether) to another dimension (overworld, aroma's mining world) but it happens with any dimension. After that I thought it happened when I tried teleporting while flying, but it also happens even if I've been standing still on the ground for over 5 minutes. 

What's also weird is sometimes I get kicked from the server and log back on I'm at a totally different location (so I'm not at the location where I got kicked at or to where I was trying to teleport) sometimes I also log back in after a kick and I'm inside blocks.

But the really annoying thing is... it's totally random when this problem happens, one time I teleport without a problem, and the other I get kicked, but it only seems to happen during teleportations between dimensions and not with teleportations within the same dimension.

**Comment by Dijkstra1** [comment]
I know when I used charged to get back cross dim or not if i am going to unloaded chunk with IC2 machines in it that will crash the server.

**Comment by McJty** [comment]
FINALLY found the error. Fixed in next release

**Comment by PandaFrog** [comment]
I'm running the latest version of rtools and rf dimensions and i still get that crash

**Comment by McJty** [comment]
Can you show me the log? Because it really can't be the same crash as that code that caused the crash is no longer part of RFTools. You have version 5.20 right?

**Comment by PandaFrog** [comment]
the crash log or the fml log? and im running 5.20

**Comment by McJty** [comment]
Both if possible. Thanks

**Comment by utoc** [comment]
Chiming in on this as well as I have the issue;  I haven't updated rfTools to .20 YET but here are some crashlogs and full server logs for your enjoyment:

Crash 2 http://bbqsauce.terron.com/cme/crash-2.txt
Full log 2 http://bbqsauce.terron.com/cme/fml-server-2.log

Crash 3 http://bbqsauce.terron.com/cme/crash-3.txt
Full log 3 http://bbqsauce.terron.com/cme/fml-server-3.log

I've had this issue persist between world resets and I am not running RF Dimensions; Lately the bug pops up during porter usage but before the world reset, I never had anyone chime in saying so.  I will update to .20 tonight though.

**Comment by McJty** [comment]
For versions below 5.20 this cash is normal. 5.20 should fix this though and that's why I need a log for 5.20 exactly

**Comment by PandaFrog** [comment]
crash report: 
[crash-2016-08-27_03.08.04-server.txt](https://github.com/McJty/RFTools/files/440481/crash-2016-08-27_03.08.04-server.txt)

fml: https://www.dropbox.com/s/wb27pcj6isxycb7/fml-server-3.log?dl=0

ever since 5.20 the crash with advanced porter as been more common about 80% of the time it crashes the server.

**Comment by McJty** [comment]
I'll investigate but this is baffling really...

**Comment by McJty** [comment]
Well ok. I found out why. Finding a solution for this is much trickier then I thought

**Comment by McJty** [comment]
I attempted another fix. Before I release this I would like people to try it out. Can you check if the latest version available here: https://drone.io/github.com/McJty/RFTools/files
solves the issue?

Please let me know how that version goes. Both clients and server need to be updated

**Comment by PandaFrog** [comment]
it seems fixed so far after using it a few times server hasn't crashed

**Comment by McJty** [comment]
Woo, I have some other people testing it too but if they also confirm it fixed then I think it is release time. Thanks!

**Comment by McJty** [comment]
Fixed in 5.21
