### ISSUE TITLE
[1.11] Crash with java.lang.NullPointerException: Rendering screen

### ISSUE THREAD

**Issue by Nullga** [McJty/RFTools#890]
Forge 13.19.0.2176
CompatLayer 0.0.39beta
McJtylib 2.2.0beta
RFTools 5.62beta1
RFTools Dimensions 4.45beta1

Game crashes when browsing dimlets in Dimlet Workbench. Quickest way to reproduce is to search "body" in the workbench and move cursor to one of dimlets come up.

http://pastebin.com/hCEJpPZ2

**Comment by McJty** [comment]
I'll check it out soon

**Comment by McJty** [comment]
Fixed next release

**Comment by Nullga** [comment]
Thank you for upgrading! I just want to let you know I still see a similar crash to this but this time only with some of special dimlets such Cheater while other dimlet types are fine.

Forge 13.19.0.2180
CompatLayer 0.1.0
McJtylib 2.3.0
RFTools 5.70
RFTools Dimensions 4.50

Logs
http://pastebin.com/CLCaP5WK
